package.path = package.path .. ";./?.lua"

local results = {}

local function runTest(name, fn)
    local ok, err = pcall(fn)
    results[#results + 1] = {name = name, ok = ok, err = err}
end

local function assertTrue(condition, message)
    if not condition then
        error(message or "assertTrue failed", 2)
    end
end

local function readFile(path)
    local file = io.open(path, "r")
    if not file then
        return nil
    end
    local content = file:read("*a")
    file:close()
    return content
end

runTest("ui_theme_defines_button_variants_tokens", function()
    local content = readFile("uiTheme.lua")
    assertTrue(type(content) == "string", "uiTheme.lua not readable")
    assertTrue(content:find("BUTTON_VARIANTS", 1, true) ~= nil, "button variants table missing")
    assertTrue(content:find("default", 1, true) ~= nil, "default variant missing")
    assertTrue(content:find("success", 1, true) ~= nil, "success variant missing")
    assertTrue(content:find("danger", 1, true) ~= nil, "danger variant missing")
    assertTrue(content:find("disabled", 1, true) ~= nil, "disabled variant missing")
    assertTrue(content:find("function uiTheme.applyButtonVariant", 1, true) ~= nil, "button variant applier missing")
end)

runTest("confirm_dialog_uses_shared_ui_theme_helpers", function()
    local content = readFile("confirmDialog.lua")
    assertTrue(type(content) == "string", "confirmDialog.lua not readable")
    assertTrue(content:find("local uiTheme = require(\"uiTheme\")", 1, true) ~= nil, "uiTheme import missing")
    assertTrue(content:find("uiTheme.drawTechPanel", 1, true) ~= nil, "confirm dialog should use shared panel renderer")
    assertTrue(content:find("uiTheme.drawButton", 1, true) ~= nil, "confirm dialog should use shared button renderer")
end)

runTest("game_log_viewer_uses_shared_ui_theme_helpers", function()
    local content = readFile("gameLogViewer.lua")
    assertTrue(type(content) == "string", "gameLogViewer.lua not readable")
    assertTrue(content:find("local uiTheme = require(\"uiTheme\")", 1, true) ~= nil, "uiTheme import missing")
    assertTrue(content:find("uiTheme.drawTechPanel", 1, true) ~= nil, "game log viewer should use shared panel renderer")
    assertTrue(content:find("uiTheme.drawButton", 1, true) ~= nil, "game log viewer should use shared button renderer")
end)

runTest("main_menu_uses_shared_button_variant_state", function()
    local content = readFile("mainMenu.lua")
    assertTrue(type(content) == "string", "mainMenu.lua not readable")
    assertTrue(content:find("uiTheme.applyButtonVariant", 1, true) ~= nil, "main menu should apply button variants")
end)

runTest("main_menu_scenario_mode_feature_enabled", function()
    local content = readFile("globals.lua")
    assertTrue(type(content) == "string", "globals.lua not readable")
    assertTrue(content:find("SCENARIO_MODE = true", 1, true) ~= nil, "scenario mode should be enabled for the main menu entry")
end)

runTest("scenario_editor_feature_enabled_for_manual_scenario_work", function()
    local globals = readFile("globals.lua")
    assertTrue(type(globals) == "string", "globals.lua not readable")
    assertTrue(globals:find("SCENARIO_EDITOR = true", 1, true) ~= nil, "scenario editor should be enabled for manual scenario work")

    local selectScreen = readFile("scenarioSelect.lua")
    assertTrue(type(selectScreen) == "string", "scenarioSelect.lua not readable")
    assertTrue(selectScreen:find("SCENARIO_EDITOR_FEATURE_ENABLED", 1, true) ~= nil, "scenario select should use the editor feature flag")
    assertTrue(selectScreen:find("if SCENARIO_EDITOR_FEATURE_ENABLED then", 1, true) ~= nil, "scenario select should create the editor button only when enabled")
end)

runTest("scenario_editor_new_scenario_uses_editor_async_generation_contract", function()
    local content = readFile("scenarioEditor.lua")
    assertTrue(type(content) == "string", "scenarioEditor.lua not readable")
    assertTrue(content:find('require, "scenario_tooling.retro_generator"', 1, true) ~= nil, "New Scenario should use scenario generator tooling")
    assertTrue(content:find('require, "scenario_tooling.quality_evaluator"', 1, true) ~= nil, "New Scenario should quality-gate generated candidates")
    assertTrue(content:find("SCENARIO_NEW_GENERATOR_ARCHETYPE", 1, true) == nil, "New Scenario should not hardcode a single generator archetype")
    assertTrue(content:find("SCENARIO_NEW_GENERATOR_ARCHETYPES", 1, true) ~= nil or content:find("generatorArchetypes", 1, true) ~= nil, "New Scenario should declare a rotating/random archetype/profile list")
    assertTrue(content:find("math.random", 1, true) ~= nil or content:find("nextGeneratorArchetype", 1, true) ~= nil or content:find("rotateGeneratorArchetype", 1, true) ~= nil, "New Scenario should randomize/rotate generator selection")
    assertTrue(content:find("maxAttempts = 1", 1, true) ~= nil, "each editor generation step should run with maxAttempts=1")
    assertTrue(content:find("maxAttempts = 48", 1, true) == nil, "legacy maxAttempts=48 should be removed from editor generation")
    assertTrue(content:find("archetype = ", 1, true) ~= nil or content:find("profile = ", 1, true) ~= nil, "New Scenario should pass selected archetype/profile into generation")
    assertTrue(content:find("onBack()", 1, true) ~= nil, "Back flow should remain wired during generation")
    assertTrue(content:find("cancel", 1, true) ~= nil or content:find("generationInProgress", 1, true) ~= nil, "generation should expose explicit cancel/back-in-progress state")
    assertTrue(content:find("button.enabled = false", 1, true) ~= nil or content:find("button.disabledVisual", 1, true) ~= nil, "generation state should disable non-Back buttons")
    assertTrue(content:find("uiButtons.newScenario.enabled = true", 1, true) ~= nil, "New Scenario should be re-enabled after generation")
    assertTrue(content:find("uiButtons.simulate.enabled = true", 1, true) ~= nil, "Simulate should be re-enabled after generation")
    assertTrue(content:find("generated_state_has_no_active_red_unit", 1, true) ~= nil, "generated editor candidates must include an active Red unit beyond Commandant")
    assertTrue(content:find("generated_state_lacks_blue_coordination", 1, true) ~= nil, "generated editor candidates must require support/finisher coordination")
    assertTrue(content:find('archetype = "support_intercepts_finisher_threat_artillery_finish"', 1, true) ~= nil, "editor pool should expose support-intercepts-artillery profile for current playtest")
    assertTrue(content:find('archetype = "support_under_real_red_pressure"', 1, true) == nil, "editor pool should not expose support-under-pressure while support-intercepts-artillery is under test")
    assertTrue(content:find('archetype = "crusher_contact_breach"', 1, true) == nil, "editor pool should not expose crusher-contact while support-intercepts-artillery is under test")
    assertTrue(content:find("allowEditorPlaytest = true", 1, true) == nil, "support-intercepts-artillery should use normal approval gates, not playtest override")
    assertTrue(content:find('archetype = "dual_rock_lock_ranged_finish"', 1, true) == nil, "editor pool should exclude dual Rock-lock until it has active Red pressure")
    assertTrue(content:find('archetype = "support_reposition_rock_los_finish"', 1, true) == nil, "editor pool should exclude Cloudstriker/Artillery LOS until it has a real false path")
    assertTrue(content:find("loadGeneratedScenarioIntoEditor(dossier, quality)", 1, true) ~= nil, "generated dossier and quality should load into editor board")
    assertTrue(content:find("Generated scenario loaded into editor.", 1, true) ~= nil, "success status should describe loaded generated scenario")
end)

runTest("scenario_editor_exports_current_board_as_playable_file", function()
    local content = readFile("scenarioEditor.lua")
    assertTrue(type(content) == "string", "scenarioEditor.lua not readable")
    assertTrue(content:find('createButton("export", "Export"', 1, true) ~= nil, "Validate button should be replaced by Export")
    assertTrue(content:find("Scenario#", 1, true) ~= nil, "exported file should use Scenario# code prefix")
    assertTrue(content:find("startSnapshot", 1, true) ~= nil, "export should write a playable scenario snapshot")
    assertTrue(content:find('SCENARIO_EXPORT_STATUS = "PROMOTED"', 1, true) ~= nil, "editor exports should be manually promoted")
    assertTrue(content:find('SCENARIO_DOSSIER_DIR = "scenario_dossiers"', 1, true) ~= nil, "editor exports should write proof sidecars")
    assertTrue(content:find("buildScenarioExportDossierContent", 1, true) ~= nil, "export should write a dossier/proof sidecar")
    assertTrue(content:find("buildScenarioExportSolutionContent", 1, true) ~= nil or content:find("solution sidecar", 1, true) ~= nil, "export should build a solution sidecar")
    assertTrue(content:find("solutionPath", 1, true) ~= nil, "export should persist solutionPath metadata")
    assertTrue(content:find("sourceSolutionStale", 1, true) ~= nil or content:find("staleSolution", 1, true) ~= nil, "export should persist stale-solution metadata")
    assertTrue(content:find("scenarioRedPolicy", 1, true) ~= nil, "export should include runtime Scenario Red Policy metadata")
    assertTrue(content:find("SCENARIO_RUNTIME_ACTION_BUDGET = 2", 1, true) ~= nil, "Scenario runtime must keep the two-action turn contract")
    assertTrue(content:find("generatedActionBudget", 1, true) == nil, "editor/export must not inflate Scenario Mode action budget from generated solution length")
    assertTrue(content:find("currentTurn = 1", 1, true) ~= nil, "editor/export runtime snapshots should start playable scenarios on turn 1")
    assertTrue(content:find("generatedState.scenarioTurn", 1, true) == nil, "editor/export runtime snapshots must not copy proof-only scenarioTurn")
end)

runTest("scenario_mode_uses_runtime_red_policy_not_standard_ai", function()
    local gameplay = readFile("gameplay.lua")
    assertTrue(type(gameplay) == "string", "gameplay.lua not readable")
    assertTrue(gameplay:find('require("scenarioRedRuntime")', 1, true) ~= nil, "scenario gameplay should use shipped runtime red policy")
    assertTrue(gameplay:find("Scenario Mode uses the verified Scenario Red Policy runtime", 1, true) ~= nil, "scenario red policy runtime path should be explicit")
    assertTrue(gameplay:find("gameMode == GAME.MODE.SINGLE_PLAYER or gameMode == GAME.MODE.AI_VS_AI or gameMode == GAME.MODE.SCENARIO", 1, true) == nil, "Scenario Mode must not initialize standard AI")
    assertTrue(gameplay:find('if gameMode == GAME.MODE.SINGLE_PLAYER or gameMode == GAME.MODE.AI_VS_AI then\n        local AiClass = require("ai")', 1, true) ~= nil, "standard AI should be lazy-loaded only for non-scenario AI modes")
    assertTrue(gameplay:find("scenarioRedVisibleDelaySec = 0", 1, true) ~= nil, "Scenario Red Policy must not add a silent delay after Red-turn handoff")
    assertTrue(gameplay:find("scenarioRedPreviewDelaySec = 0.35", 1, true) ~= nil, "Scenario Red Policy should stage visible previews before acting")
    assertTrue(gameplay:find("showScenarioRedPolicyCommandPreview", 1, true) ~= nil, "Scenario Red Policy should render previews before runtime actions")
    assertTrue(gameplay:find("GAME.CURRENT.AI_PANEL_STATUS", 1, true) ~= nil, "Scenario Red Policy should surface thinking status in the turn panel")
    assertTrue(gameplay:find("resetScenarioRedPolicyCandidate", 1, true) ~= nil, "Scenario Red Policy delay state should reset outside eligible Red action windows")

    local runtime = readFile("scenarioRedRuntime.lua")
    assertTrue(type(runtime) == "string", "scenarioRedRuntime.lua not readable")
    assertTrue(runtime:find('require("scenarioRedPolicy")', 1, true) ~= nil, "runtime should depend on shipped scenario red policy")
    assertTrue(runtime:find('require("scenarioStateEngine")', 1, true) ~= nil, "runtime should depend on shipped scenario state engine")
    assertTrue(runtime:find("scenario_tooling", 1, true) == nil, "runtime red policy adapter must not depend on internal scenario tooling")
    assertTrue(runtime:find('require("ai', 1, true) == nil, "runtime red policy must not require standard AI")

    local policy = readFile("scenarioRedPolicy.lua")
    assertTrue(type(policy) == "string", "scenarioRedPolicy.lua not readable")
    assertTrue(policy:find('require("scenarioStateEngine")', 1, true) ~= nil, "shipped policy should use shipped scenario state engine")
    assertTrue(policy:find('require("scenarioRulesKernel")', 1, true) ~= nil, "shipped policy should use shipped scenario rules kernel")
    assertTrue(policy:find("scenario_tooling", 1, true) == nil, "shipped policy must not depend on internal generator/proof tooling")
end)

runTest("scenario_select_launches_playable_runtime_policy", function()
    local content = readFile("scenarioSelect.lua")
    assertTrue(type(content) == "string", "scenarioSelect.lua not readable")
    assertTrue(content:find("scenarioRedPolicy", 1, true) ~= nil, "loaded scenario definitions should preserve Scenario Red Policy metadata")
    assertTrue(content:find("PROMOTED_SCENARIO_STATUSES", 1, true) ~= nil, "final scenario list should define promoted/approved statuses")
    assertTrue(content:find("if not isPromotedScenarioPayload(rowData) then", 1, true) ~= nil, "final scenario list should keep non-promoted internal files hidden")
    assertTrue(content:find("buildPlayableScenarioRedPolicyConfig", 1, true) ~= nil, "loaded scenarios should receive default playable Scenario Red Policy config")
    assertTrue(content:find('stateMachineRef.changeState("scenarioGameplay")', 1, true) ~= nil, "scenario list should open selected scenarios into playable runtime")
    assertTrue(content:find("Loading %s with Scenario Red Policy.", 1, true) ~= nil, "scenario launch status should make runtime policy explicit")
end)

runTest("scenario_select_shows_creator_and_persists_progress", function()
    local content = readFile("scenarioSelect.lua")
    assertTrue(type(content) == "string", "scenarioSelect.lua not readable")
    assertTrue(content:find('DEFAULT_SCENARIO_CREATED_BY = "Flippet Cat"', 1, true) ~= nil, "scenario list should default creator metadata")
    assertTrue(content:find('"Created by"', 1, true) ~= nil, "scenario list should replace Status column with Created by")
    assertTrue(content:find('love.graphics.printf("Status"', 1, true) == nil, "scenario list should not render a Status column")
    assertTrue(content:find('require("scenario_progress")', 1, true) ~= nil, "scenario list should use the shared progress persistence module")
    assertTrue(content:find("scenarioProgress.load()", 1, true) ~= nil, "scenario list should load progress from the save file")
    assertTrue(content:find("scenarioProgress.applyResult(result)", 1, true) ~= nil, "scenario results should persist through the shared module")
    assertTrue(content:find("applyPendingScenarioResult(consumePendingScenarioResult())", 1, true) ~= nil, "scenario results should update progress before rows rebuild")
    assertTrue(content:find("attemptRecorded = false", 1, true) ~= nil, "scenario attempts should be recorded by gameplay entry, not only pre-counted in the list")

    local gameplay = readFile("gameplay.lua")
    assertTrue(type(gameplay) == "string", "gameplay.lua not readable")
    assertTrue(gameplay:find("scenarioProgress.recordAttempt(scenarioId)", 1, true) ~= nil, "scenario gameplay should persist attempts immediately")
    assertTrue(gameplay:find('recordScenarioAttemptStart("enter")', 1, true) ~= nil, "scenario gameplay should increment attempts when an attempt starts")
    assertTrue(gameplay:find('recordScenarioAttemptStart("retry")', 1, true) ~= nil, "scenario retry should increment attempts immediately")
end)

runTest("scenario_gameplay_state_registered_when_feature_enabled", function()
    local content = readFile("stateMachine.lua")
    assertTrue(type(content) == "string", "stateMachine.lua not readable")
    assertTrue(content:find('states.scenarioGameplay = require("scenarioGameplay")', 1, true) ~= nil, "scenarioGameplay state must be registered or Simulate opens a blank state")
end)

runTest("scenario_runtime_runs_commandant_defense_before_red_policy", function()
    local content = readFile("gameRuler.lua")
    assertTrue(type(content) == "string", "gameRuler.lua not readable")
    assertTrue(content:find("local scenarioMode = self:isScenarioMode()", 1, true) ~= nil, "Scenario Mode branch should be explicit and reusable inside turn finalization")
    assertTrue(content:find("self.currentTurnPhase = TURN_PHASES.COMMAND_HUB", 1, true) ~= nil, "Red Scenario turns should enter Commandant Defense before actions")
    assertTrue(content:find("if scenarioMode and self.currentPlayer == 1 then", 1, true) ~= nil, "Blue Scenario turns should skip Commandant Defense")
    assertTrue(content:find("self.currentTurnPhase = TURN_PHASES.ACTIONS", 1, true) ~= nil, "Blue Scenario turns should enter actions directly")
    assertTrue(content:find("Scenario-only Red handoff: show the Red turn presentation before Commandant defense.", 1, true) ~= nil, "Scenario Mode should show Red turn presentation before Commandant Defense")
    assertTrue(content:find("Commandant defense is a turn rule. Scenario Red Policy starts only after", 1, true) ~= nil, "Scenario Mode should document commandant defense before policy")
    assertTrue(content:find("SCENARIO_COMMAND_HUB_DEFENSE_TIMING", 1, true) ~= nil, "Scenario Mode should have explicit Commandant Defense timing")
    assertTrue(content:find("STANDARD_COMMAND_HUB_DEFENSE_TIMING", 1, true) ~= nil, "standard Commandant Defense timing should remain separate")
    assertTrue(content:find("scanStepDelay = 0.4", 1, true) ~= nil, "standard Commandant Defense scan pacing should be preserved")
    assertTrue(content:find("startDelay = 0", 1, true) ~= nil, "Scenario Commandant Defense should begin immediately after Red handoff")
    assertTrue(content:find("completeDelay = 0", 1, true) ~= nil, "Scenario Commandant Defense should not add a silent tail before Red Policy")
    assertTrue(content:find("blocked = self:isScenarioTurnHandoffBlocked()", 1, true) ~= nil, "Scenario Commandant Defense should use the Scenario handoff blocker")
    assertTrue(content:find("local commandHubTiming = self:getCommandHubDefenseTiming()", 1, true) ~= nil, "turn transition should use mode-specific Commandant Defense timing")
    assertTrue(content:find("function gameRuler:isScenarioRedPolicyAnimationBlocked()", 1, true) ~= nil, "Scenario Red Policy should have a dedicated animation gate")
    assertTrue(content:find("function gameRuler:isScenarioTurnHandoffBlocked()", 1, true) ~= nil, "Scenario turn handoff should have a dedicated animation gate")
    assertTrue(content:find("Blue starts directly in", 1, true) ~= nil, "Scenario Mode should document the Blue Commandant-phase skip")

    local gameplay = readFile("gameplay.lua")
    assertTrue(type(gameplay) == "string", "gameplay.lua not readable")
    assertTrue(gameplay:find("not gameRuler:isScenarioRedPolicyAnimationBlocked()", 1, true) ~= nil, "Scenario Red Policy should not wait for non-blocking Commandant Defense visuals")
    assertTrue(gameplay:find("not gameRuler:isScenarioTurnHandoffBlocked()", 1, true) ~= nil, "Scenario turn handoff should not wait for residual visual effects")

    local uiContent = readFile("uiClass.lua")
    assertTrue(type(uiContent) == "string", "uiClass.lua not readable")
    assertTrue(uiContent:find("Scenario Mode shows Commandant Defense as its own phase", 1, true) ~= nil, "Scenario UI should not hide Commandant Defense behind the thinking spinner")
    assertTrue(uiContent:find('and phaseInfo.turnPhaseName == "actions"', 1, true) ~= nil, "Scenario Red thinking panel should appear only during Red actions")
    assertTrue(uiContent:find("local scenarioMode = self.gameRuler.isScenarioMode and self.gameRuler:isScenarioMode()", 1, true) ~= nil, "Scenario commandant UI should not enqueue duplicate auto-advances")
end)

runTest("main_menu_local_routes_direct_to_local_flow", function()
    local content = readFile("mainMenu.lua")
    assertTrue(type(content) == "string", "mainMenu.lua not readable")
    assertTrue(content:find("startLocalMultiplayerFromMenu", 1, true) ~= nil, "main menu should route local multiplayer through direct helper")
    assertTrue(content:find('changeState("localMultiplayerMenu")', 1, true) == nil, "main menu should not route through local multiplayer submenu")
end)

runTest("main_menu_remote_play_overlay_starts_local_remote_variant", function()
    local content = readFile("mainMenu.lua")
    assertTrue(type(content) == "string", "mainMenu.lua not readable")
    assertTrue(content:find("hasActiveRemotePlaySession", 1, true) ~= nil, "main menu should detect active remote play session")
    assertTrue(content:find('startNewModeFlow(GAME.MODE.MULTYPLAYER_LOCAL, "remote_play")', 1, true) ~= nil, "remote play overlay should start direct local remote variant")
    assertTrue(content:find('startModeWithResumePrompt(GAME.MODE.MULTYPLAYER_LOCAL)', 1, true) ~= nil, "couch local resume flow should remain available")

    local factionContent = readFile("factionSelect.lua")
    assertTrue(type(factionContent) == "string", "factionSelect.lua not readable")
    assertTrue(factionContent:find("isRemotePlayLocalVariant", 1, true) ~= nil, "faction should use remote play local variant helper")
    assertTrue(factionContent:find("isOnlineMode", 1, true) ~= nil, "faction should keep online and remote play paths separate")
end)

runTest("online_lobby_uses_shared_button_variant_state", function()
    local content = readFile("onlineLobby.lua")
    assertTrue(type(content) == "string", "onlineLobby.lua not readable")
    assertTrue(content:find("uiTheme.applyButtonVariant", 1, true) ~= nil, "online lobby should apply button variants")
    assertTrue(content:find("button.disabledVisual", 1, true) ~= nil, "online lobby should expose disabled visual state")
end)

runTest("online_leaderboard_uses_shared_button_variant_state", function()
    local content = readFile("onlineLeaderboard.lua")
    assertTrue(type(content) == "string", "onlineLeaderboard.lua not readable")
    assertTrue(content:find("uiTheme.applyButtonVariant", 1, true) ~= nil, "online leaderboard should apply button variants")
    assertTrue(content:find("button.disabledVisual", 1, true) ~= nil, "online leaderboard should expose disabled visual state")
end)

runTest("input_backend_steam_input_states_cover_primary_screens", function()
    local content = readFile("input_backend.lua")
    assertTrue(type(content) == "string", "input_backend.lua not readable")
    for _, stateName in ipairs({"mainMenu", "factionSelect", "gameplay", "onlineLobby", "onlineLeaderboard"}) do
        assertTrue(content:find(stateName, 1, true) ~= nil, "steam input state coverage missing: " .. stateName)
    end
end)

runTest("faction_select_uses_shared_button_tokens", function()
    local content = readFile("factionSelect.lua")
    assertTrue(type(content) == "string", "factionSelect.lua not readable")
    assertTrue(content:find("uiTheme.BUTTON_VARIANTS.default", 1, true) ~= nil, "faction select should source default button tokens from uiTheme")
    assertTrue(content:find("uiTheme.BUTTON_VARIANTS.success", 1, true) ~= nil, "faction select should source success tokens from uiTheme")
    assertTrue(content:find("uiTheme.BUTTON_VARIANTS.disabled", 1, true) ~= nil, "faction select should source disabled tokens from uiTheme")
end)

runTest("uiclass_theme_bridge_uses_ui_theme_palette", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find("local uiTheme = require(\"uiTheme\")", 1, true) ~= nil, "uiClass should import uiTheme")
    assertTrue(content:find("function uiClass:createDefaultColorTheme()", 1, true) ~= nil, "uiClass theme bridge helper missing")
    assertTrue(content:find("local colors = uiTheme.COLORS", 1, true) ~= nil, "uiClass default theme should source base palette from uiTheme")
end)

runTest("gameplay_online_escape_routes_to_concede_confirm", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("Concede match? This will count as a forfeit.", 1, true) ~= nil, "online concede confirm copy missing")
    assertTrue(content:find("requestSurrenderFromUi()", 1, true) ~= nil, "online concede confirm must route to surrender")
end)

runTest("gameplay_elo_summary_has_center_modal_and_close_button", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("ONLINE RATING UPDATE", 1, true) ~= nil, "centered rating modal title missing")
    assertTrue(content:find("local function hasVisibleOnlineEloSummary()", 1, true) ~= nil, "rating visibility helper missing")
    assertTrue(content:find("onlineEloCloseButtonBounds", 1, true) ~= nil, "rating close button bounds state missing")
    assertTrue(content:find("dismissOnlineEloSummary", 1, true) ~= nil, "rating dismiss helper missing")
end)

runTest("gameplay_objective_modal_present_with_expected_copy", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("WIN CONDITIONS", 1, true) ~= nil, "objective modal title missing")
    assertTrue(content:find("Defeat the enemy Commandant or all enemy units.", 1, true) ~= nil, "objective modal body copy missing")
end)

runTest("gameplay_unit_codex_overlay_exists", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("UNIT CODEX", 1, true) ~= nil, "unit codex title missing")
    assertTrue(content:find("UNIT_CODEX_UNIT_ORDER", 1, true) ~= nil, "unit codex order missing")
    assertTrue(content:find("drawUnitCodexOverlay", 1, true) ~= nil, "unit codex draw helper missing")
    assertTrue(content:find("buildUnitCodexCounts", 1, true) ~= nil, "unit codex count helper missing")
    assertTrue(content:find("unitCodexGridCaches", 1, true) ~= nil, "unit codex cache state missing")
    assertTrue(content:find("buildUnitCodexGridCache", 1, true) ~= nil, "unit codex grid cache builder missing")
    assertTrue(content:find("ensureUnitCodexGridCache", 1, true) ~= nil, "unit codex cache lookup missing")
end)

runTest("gameplay_unit_codex_overlay_uses_two_rows_of_four_cards", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("% 4", 1, true) ~= nil, "codex should lay cards out across 4 columns")
    assertTrue(content:find("/ 4", 1, true) ~= nil or content:find("math.floor((index - 1) / 4)", 1, true) ~= nil, "codex should lay cards out across 2 rows")
end)

runTest("gameplay_unit_codex_open_button_exists", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find([[UNIT_CODEX_OPEN_LABEL = "UNIT CODEX"]], 1, true) ~= nil, "codex button label missing")
    assertTrue(content:find("drawUnitCodexOpenButton", 1, true) ~= nil, "codex open button draw helper missing")
    assertTrue(content:find("unitCodexCloseButtonBounds", 1, true) ~= nil, "codex close button state missing")
    assertTrue(content:find("unitCodexToggleButtonBounds", 1, true) ~= nil, "codex faction toggle button state missing")
    assertTrue(content:find("unitCodexFocusedButton", 1, true) ~= nil, "codex focused button state missing")
    assertTrue(content:find("ui.unitCodexButton", 1, true) ~= nil or content:find("self.unitCodexButton", 1, true) ~= nil, "codex button should live in the side column layout")
end)

runTest("gameplay_unit_codex_close_accepts_keyboard_confirm", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find('key == "return" or key == "space"', 1, true) ~= nil, "codex close keys should include return and space")
    assertTrue(content:find('key == "w" or key == "up"', 1, true) ~= nil, "codex should support up navigation")
    assertTrue(content:find('key == "s" or key == "down"', 1, true) ~= nil, "codex should support down navigation")
end)

runTest("gameplay_unit_codex_faction_switch_button_exists", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("getUnitCodexToggleButtonLabel", 1, true) ~= nil, "codex faction toggle label helper missing")
    assertTrue(content:find('SHOW OTHER FACTION', 1, true) ~= nil, "codex faction toggle label missing")
    assertTrue(content:find("switchUnitCodexFaction", 1, true) ~= nil, "codex faction switch helper missing")
    assertTrue(content:find("unitCodexTransitionElapsed", 1, true) ~= nil, "codex transition state missing")
    assertTrue(content:find([[getUnitCodexFactionName(displayFaction) .. " FACTION"]], 1, true) == nil, "codex faction subtitle should not be drawn")
end)

runTest("gameplay_unit_codex_button_uses_side_column_layout", function()
    local gameplayContent = readFile("gameplay.lua")
    local uiContent = readFile("uiClass.lua")
    assertTrue(type(gameplayContent) == "string", "gameplay.lua not readable")
    assertTrue(type(uiContent) == "string", "uiClass.lua not readable")
    assertTrue(gameplayContent:find([[UNIT_CODEX_OPEN_LABEL = "UNIT CODEX"]], 1, true) ~= nil, "codex side button label should be UNIT CODEX")
    assertTrue(uiContent:find("self.unitCodexButton", 1, true) ~= nil, "uiClass should track unitCodexButton bounds")
    assertTrue(uiContent:find('name = "unitCodexButton"', 1, true) ~= nil, "unitCodexButton should be added to ui elements")
    assertTrue(uiContent:find('currentElement.name == "unitCodexButton"', 1, true) ~= nil, "unitCodexButton navigation branch missing")
end)

runTest("gameplay_shoulder_shortcuts_focus_supply_panels", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("local function handleSupplyPanelShortcutKey", 1, true) ~= nil, "supply panel shortcut helper missing")
    assertTrue(content:find('if key == "q" then', 1, true) ~= nil, "left shoulder shortcut should map to q")
    assertTrue(content:find("return focusSupplyPanel(1)", 1, true) ~= nil, "left shoulder shortcut should focus left supply panel")
    assertTrue(content:find("return focusSupplyPanel(2)", 1, true) ~= nil, "right shoulder shortcut should focus right supply panel")
end)

runTest("gameplay_unit_codex_is_non_pausing_input_overlay", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("drawUnitCodexOverlay()", 1, true) ~= nil, "codex overlay draw call missing")
    assertTrue(content:find("if hasVisibleUnitCodexOverlay() then", 1, true) ~= nil, "codex visibility gate missing")
    assertTrue(content:find("grid:updateAnimations(animationDt)", 1, true) ~= nil, "gameplay update should keep running under codex overlay")
    assertTrue(content:find("ui.overlayInputBlocked", 1, true) ~= nil, "ui overlay hover/input suppression flag missing")
end)

runTest("uiclass_draw_unit_info_content_uses_cached_unit_images", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find("self:getUnitImage(unit, player)", 1, true) ~= nil, "unit info content should use cached unit image lookup")
    assertTrue(content:find("pcall(love.graphics.newImage, iconPath)", 1, true) == nil, "unit info content should not create icon images every draw")
end)

runTest("uiclass_info_gloss_overlay_helper_exists", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find("function uiClass:drawInfoCardGlossOverlay", 1, true) ~= nil, "gloss overlay helper missing")
    assertTrue(content:find("content.disableGloss", 1, true) ~= nil, "card draw should support gloss suppression for cached codex cards")
end)

runTest("uiclass_suppresses_underlay_hover_when_overlay_blocks_input", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find("if self.overlayInputBlocked then", 1, true) ~= nil, "uiClass should suppress hover/click when overlay blocks input")
    assertTrue(content:find("modalActive = (GameLogViewer and GameLogViewer.isActive and GameLogViewer.isActive()) or confirmDialogActive or self.overlayInputBlocked == true", 1, true) ~= nil, "game log panel should suppress hover when overlay is open")
end)

runTest("objective_modal_remote_play_includes_no_elo_line", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("Remote Play Together match: online rating is not affected.", 1, true) ~= nil, "remote play no-rating objective line missing")
end)

runTest("gameplay_objective_modal_button_label_orders_received", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("Orders Received", 1, true) ~= nil, "objective modal CTA label missing")
end)

runTest("gameplay_objective_modal_blocks_underlying_input_until_dismissed", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("hasVisibleMatchObjectiveModal()", 1, true) ~= nil, "objective modal visibility gate missing")
    assertTrue(content:find("handleMatchObjectiveModalClick", 1, true) ~= nil, "objective modal click gate missing")
    assertTrue(content:find("-- Keep objective modal focus locked until closed.", 1, true) ~= nil, "objective modal lock behavior missing")
end)

runTest("gameplay_objective_modal_close_keys_mouse_keyboard_gamepad_supported", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("isMatchObjectiveCloseKey", 1, true) ~= nil, "objective modal close key helper missing")
    assertTrue(content:find('key == "escape" or key == "return" or key == "space"', 1, true) ~= nil, "objective modal close keys missing")
    assertTrue(content:find("gamepad_a_close", 1, true) ~= nil, "objective modal gamepad A close missing")
    assertTrue(content:find("gamepad_cancel_close", 1, true) ~= nil, "objective modal gamepad cancel close missing")
end)

runTest("gameplay_objective_modal_skips_resume_path", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("restoredFromResumeSnapshot", 1, true) ~= nil, "resume restore tracking missing")
    assertTrue(content:find("matchObjectiveModalVisible = false", 1, true) ~= nil, "objective modal baseline reset missing")
    assertTrue(content:find("elseif (not restoredFromResumeSnapshot) and (not restoredFromScenarioSnapshot)", 1, true) ~= nil, "objective modal should skip resume and scenario-restore paths")
    assertTrue(content:find("onlineAutoAdvanceState.showMatchObjectiveModal({})", 1, true) ~= nil, "default objective modal should be shown only on fresh start")
end)

runTest("main_menu_click_dispatch_uses_declared_trigger_handler", function()
    local content = readFile("mainMenu.lua")
    assertTrue(type(content) == "string", "mainMenu.lua not readable")
    assertTrue(content:find("local triggerSelectedButton", 1, true) ~= nil, "triggerSelectedButton forward declaration missing")
    assertTrue(content:find("triggerSelectedButton = function(selectedButton)", 1, true) ~= nil, "triggerSelectedButton assignment missing")
    assertTrue(content:find("triggerSelectedButton(hoveredButton)", 1, true) ~= nil, "main menu mouse click should dispatch through triggerSelectedButton")
end)

runTest("gameover_battlefield_view_suppresses_action_panels", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find("battlefieldGameOverView", 1, true) ~= nil, "battlefield game-over guard missing")
    assertTrue(content:find("if not battlefieldGameOverView then", 1, true) ~= nil, "battlefield game-over panel suppression missing")
end)

runTest("faction_start_disabled_has_no_overlay_glyph", function()
    local content = readFile("factionSelect.lua")
    assertTrue(type(content) == "string", "factionSelect.lua not readable")
    assertTrue(content:find('love.graphics.printf("X"', 1, true) == nil, "disabled Start should not render X glyph")
    assertTrue(content:find('love.graphics.print("X"', 1, true) == nil, "disabled Start should not render X glyph")
end)

runTest("faction_remote_play_start_gate_present", function()
    local content = readFile("factionSelect.lua")
    assertTrue(type(content) == "string", "factionSelect.lua not readable")
    assertTrue(content:find("isRemotePlayLocalVariant", 1, true) ~= nil, "remote play variant helper missing")
    assertTrue(content:find("getRemotePlaySessionCount", 1, true) ~= nil, "remote play session count gate missing")
    assertTrue(content:find("canStartLocalMatch", 1, true) ~= nil, "remote play start readiness helper missing")
end)

runTest("local_multiplayer_submenu_removed", function()
    local menuContent = readFile("localMultiplayerMenu.lua")
    assertTrue(menuContent == nil, "localMultiplayerMenu.lua should be removed")

    local stateMachineContent = readFile("stateMachine.lua")
    assertTrue(type(stateMachineContent) == "string", "stateMachine.lua not readable")
    assertTrue(stateMachineContent:find('require("localMultiplayerMenu")', 1, true) == nil, "state machine should not reference localMultiplayerMenu")
end)

runTest("faction_remote_status_text_removed", function()
    local factionContent = readFile("factionSelect.lua")
    assertTrue(type(factionContent) == "string", "factionSelect.lua not readable")
    assertTrue(factionContent:find("No guest session", 1, true) == nil, "faction should not show remote status text")
    assertTrue(factionContent:find("Waiting for Remote Play guest...", 1, true) == nil, "faction should not show remote waiting status text")
    assertTrue(factionContent:find('love.graphics.printf(statusText', 1, true) == nil, "faction should not draw remote status text")
    assertTrue(factionContent:find("RemotePlay] Guest connected but no input detected", 1, true) ~= nil, "one-time remote input warning log missing")
end)

runTest("remote_play_green_input_detected_text_removed", function()
    local factionContent = readFile("factionSelect.lua")
    assertTrue(type(factionContent) == "string", "factionSelect.lua not readable")
    assertTrue(factionContent:find("Guest input detected", 1, true) == nil, "faction should not show green input-detected text")
end)

runTest("reaction_buttons_replace_hidden_phase_button_space_on_non_local_turn", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find("drawOnlineReactionButtons", 1, true) ~= nil, "reaction button renderer missing")
    assertTrue(content:find("self:isOnlineNonLocalTurn(phaseInfo)", 1, true) ~= nil, "non-local turn guard missing")
end)

runTest("automatic_online_phase_button_is_hidden_except_commandant_confirm", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find("shouldHideAutomaticOnlinePhaseButton", 1, true) ~= nil, "auto phase-button visibility helper missing")
    assertTrue(content:find('if actionType == "confirmCommandHub" then', 1, true) ~= nil, "commandant confirm should stay manual")
    assertTrue(content:find('if currentPhase == "setup" then', 1, true) ~= nil, "setup auto action should hide phase button")
    assertTrue(content:find('if currentPhase == "deploy1_units" or currentPhase == "deploy2_units" then', 1, true) ~= nil, "deployment auto action should hide phase button")
    assertTrue(content:find('if currentPhase == "turn" and turnPhaseName == "actions" then', 1, true) ~= nil, "actions auto end-turn should hide phase button")
end)

runTest("automatic_local_multiplayer_phase_button_is_hidden_except_commandant_confirm", function()
    local uiContent = readFile("uiClass.lua")
    local gameplayContent = readFile("gameplay.lua")
    assertTrue(type(uiContent) == "string", "uiClass.lua not readable")
    assertTrue(type(gameplayContent) == "string", "gameplay.lua not readable")
    assertTrue(uiContent:find("mode ~= GAME.MODE.SINGLE_PLAYER and mode ~= GAME.MODE.MULTYPLAYER_LOCAL", 1, true) ~= nil, "local multiplayer should use automatic phase-button hiding")
    assertTrue(uiContent:find('if actionType == "confirmCommandHub" then', 1, true) ~= nil, "commandant confirm should stay manual in local multiplayer")
    assertTrue(gameplayContent:find("local isLocalMultiplayer = mode == GAME.MODE.MULTYPLAYER_LOCAL", 1, true) ~= nil, "local multiplayer auto-advance mode guard missing")
    assertTrue(gameplayContent:find("or (not isSinglePlayer and not isLocalMultiplayer)", 1, true) ~= nil, "local multiplayer auto-advance enable condition missing")
end)

runTest("reaction_buttons_join_readonly_allowed_ui_controls", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("isReadOnlyUiControlName", 1, true) ~= nil, "read-only UI helper missing")
    assertTrue(content:find("reactionButton_", 1, true) ~= nil, "reaction buttons should join read-only whitelist")
end)

runTest("reaction_notification_is_non_interactive_and_time_limited", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find("ONLINE_REACTION_NOTIFICATION_DURATION = 3.0", 1, true) ~= nil, "reaction notification duration missing")
    assertTrue(content:find("drawOnlineReactionNotification", 1, true) ~= nil, "reaction notification renderer missing")
end)

runTest("reaction_buttons_use_neutral_style_only", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find('variant = "default"', 1, true) ~= nil, "reaction buttons should use neutral default variant")
    assertTrue(content:find('variant = "success"', 1, true) == nil, "reaction buttons should not use success variant")
    assertTrue(content:find('variant = "danger"', 1, true) == nil, "reaction buttons should not use danger variant")
end)

runTest("reaction_buttons_center_labels_and_skip_disabled_focus", function()
    local uiContent = readFile("uiClass.lua")
    local themeContent = readFile("uiTheme.lua")
    assertTrue(type(uiContent) == "string", "uiClass.lua not readable")
    assertTrue(type(themeContent) == "string", "uiTheme.lua not readable")
    assertTrue(uiContent:find("button.centerText = true", 1, true) ~= nil, "reaction buttons should enable centered text")
    assertTrue(uiContent:find("element.disabled ~= true", 1, true) ~= nil, "reaction navigation should skip disabled buttons")
    assertTrue(themeContent:find("button.centerText == true", 1, true) ~= nil, "theme should honor centered button text")
end)

runTest("reaction_row_navigation_returns_to_surrender_button", function()
    local content = readFile("uiClass.lua")
    assertTrue(type(content) == "string", "uiClass.lua not readable")
    assertTrue(content:find('currentElement.name == "surrenderButton"', 1, true) ~= nil, "surrender navigation block missing")
    assertTrue(content:find('self:isReactionButtonName(currentElement.name)', 1, true) ~= nil, "reaction navigation block missing")
    assertTrue(content:find('element.name == "surrenderButton"', 1, true) ~= nil, "reaction up-navigation should target surrender button")
end)

runTest("main_menu_online_disabled_when_remote_play_session_connected", function()
    local content = readFile("mainMenu.lua")
    assertTrue(type(content) == "string", "mainMenu.lua not readable")
    assertTrue(content:find("getRemotePlaySessionCount", 1, true) ~= nil, "main menu should query remote play sessions")
    assertTrue(content:find("onlineReady and not remotePlayActive", 1, true) ~= nil, "online button should be disabled while remote play session is active")
end)

runTest("remote_play_exit_sets_one_shot_overlay_end_session_prompt", function()
    local stateMachineContent = readFile("stateMachine.lua")
    assertTrue(type(stateMachineContent) == "string", "stateMachine.lua not readable")
    assertTrue(stateMachineContent:find("REMOTE_PLAY_EXIT_PROMPT_PENDING", 1, true) ~= nil, "state machine should queue remote play exit prompt flag")

    local menuContent = readFile("mainMenu.lua")
    assertTrue(type(menuContent) == "string", "mainMenu.lua not readable")
    assertTrue(menuContent:find("Remote Play session is still active. End session from Steam Overlay.", 1, true) ~= nil, "main menu remote-play active prompt copy missing")
end)

runTest("remote_play_exit_prompt_consumed_once", function()
    local content = readFile("mainMenu.lua")
    assertTrue(type(content) == "string", "mainMenu.lua not readable")
    assertTrue(content:find("consumeRemotePlayExitPrompt", 1, true) ~= nil, "prompt consume helper missing")
    assertTrue(content:find("REMOTE_PLAY_EXIT_PROMPT_PENDING = false", 1, true) ~= nil, "prompt flag should be cleared after consumption")
end)

runTest("online_leaderboard_list_and_button_navigation_are_split", function()
    local content = readFile("onlineLeaderboard.lua")
    assertTrue(type(content) == "string", "onlineLeaderboard.lua not readable")
    assertTrue(content:find("local function focusLeaderboardButtons()", 1, true) ~= nil, "leaderboard button focus helper missing")
    assertTrue(content:find('if not listFocus then', 1, true) ~= nil, "leaderboard should handle up/down differently for list and buttons")
    assertTrue(content:find('if nextIndex > #leaderboardRows then', 1, true) ~= nil, "leaderboard down-from-last-row boundary missing")
    assertTrue(content:find("focusLeaderboardButtons()", 1, true) ~= nil, "leaderboard should move focus to buttons from list")
    assertTrue(content:find('key == "left" or key == "a" or key == "q"', 1, true) ~= nil, "leaderboard left navigation should accept q")
    assertTrue(content:find('key == "right" or key == "d" or key == "e"', 1, true) ~= nil, "leaderboard right navigation should accept e")
end)

runTest("online_lobby_list_and_button_navigation_are_split", function()
    local content = readFile("onlineLobby.lua")
    assertTrue(type(content) == "string", "onlineLobby.lua not readable")
    assertTrue(content:find("local function focusLobbyButtons()", 1, true) ~= nil, "online lobby button focus helper missing")
    assertTrue(content:find("local function ensureValidLobbyButtonSelection()", 1, true) ~= nil, "online lobby enabled-button helper missing")
    assertTrue(content:find('if #lobbyList == 0 then', 1, true) ~= nil, "online lobby should fall back to buttons when list is empty")
    assertTrue(content:find('key == "left" or key == "a" or key == "q"', 1, true) ~= nil, "online lobby left navigation should accept q")
    assertTrue(content:find('key == "right" or key == "d" or key == "e"', 1, true) ~= nil, "online lobby right navigation should accept e")
end)

runTest("faction_select_does_not_force_mouse_hover_on_enter", function()
    local content = readFile("factionSelect.lua")
    assertTrue(type(content) == "string", "factionSelect.lua not readable")
    assertTrue(content:find("love.mouse.setPosition(buttonCenterX, buttonCenterY)", 1, true) == nil, "faction select should not warp mouse on enter")
    assertTrue(content:find("factionSelect.mousemoved(buttonCenterX, buttonCenterY, 0, 0, false)", 1, true) == nil, "faction select should not force mouse hover mode on enter")
end)

runTest("windows_conf_console_disabled", function()
    local content = readFile("conf.lua")
    assertTrue(type(content) == "string", "conf.lua not readable")
    assertTrue(content:find("t.console = false", 1, true) ~= nil, "Windows console should be disabled on launch")
end)

runTest("elo_modal_blocks_underlying_gameover_navigation_when_visible", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("if hasVisibleOnlineEloSummary() then", 1, true) ~= nil, "rating modal gate missing")
    assertTrue(content:find("-- Keep rating modal focus locked until closed.", 1, true) ~= nil, "rating modal lock comment/behavior missing")
end)

runTest("online_elo_summary_draws_after_session_detach", function()
    local content = readFile("gameplay.lua")
    assertTrue(content:find("local function drawOnlineEloSummary()", 1, true) ~= nil, "drawOnlineEloSummary missing")
    assertTrue(content:find("if gameMode ~= GAME.MODE.MULTYPLAYER_NET or not gameRuler or gameRuler.currentPhase ~= \"gameOver\" then", 1, true) ~= nil, "drawOnlineEloSummary should not require active online session to stay visible")
end)

runTest("online_elo_summary_show_resets_transient_inputs", function()
    local content = readFile("gameplay.lua")
    assertTrue(content:find("resetTransientInputs(\"online_elo_summary_show\")", 1, true) ~= nil, "online elo summary show should reset transient inputs")
end)

runTest("gameover_focus_is_restored_after_modal_close", function()
    local content = readFile("gameplay.lua")
    assertTrue(type(content) == "string", "gameplay.lua not readable")
    assertTrue(content:find("local function ensureGameOverUIFocus", 1, true) ~= nil, "game over focus restore helper missing")
    assertTrue(content:find("ensureGameOverUIFocus(true)", 1, true) ~= nil, "elo modal dismiss should restore game over focus")
    assertTrue(content:find("ensureGameOverUIFocus(panelVisible)", 1, true) ~= nil, "game over key handling should restore focus before routing confirm")
end)

local passed = 0
for _, result in ipairs(results) do
    if result.ok then
        passed = passed + 1
        print("[PASS] " .. result.name)
    else
        print("[FAIL] " .. result.name .. " -> " .. tostring(result.err))
    end
end

print(string.format("ui_consistency_smoke: %d/%d passed", passed, #results))
if passed ~= #results then
    os.exit(1)
end
